<?php

/**
 * @file
 * The file for the giv_din_stemme theme.
 */

/**
 * Implements hook theme_suggestions_input_alter().
 */
function giv_din_stemme_theme_theme_suggestions_input_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#attributes']['fa-icon'])) {
    $suggestions[] = 'input__submit__icon';
  }
}

/**
 * Implements hook_theme_suggestions_container_alter().
 */
function giv_din_stemme_theme_theme_suggestions_container_alter(array &$suggestions, array $variables, $hook) {
  if (isset($variables['element']['#id'])) {
    $suggestions[] = $hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }
}

/**
 * Implements hook_theme_suggestions_form_element_alter().
 */
function giv_din_stemme_theme_theme_suggestions_form_element_alter(array &$suggestions, array $variables, $hook) {
  if (isset($variables['element']['#field_name'])) {
    $suggestions[] = $hook . '__' . str_replace('-', '_', $variables['element']['#field_name']);
  }
  elseif (isset($variables['element']['#title'])) {
    $suggestions[] = $hook . '__' . str_replace('-', '_', strtolower($variables['element']['#title']));
  }
}

/**
 * Implements hook_preprocess_form_element().
 */
function giv_din_stemme_theme_preprocess_form_element(&$variables) {
  if ('field_e_mail[0][value]' === $variables['name']) {
    $state = \Drupal::state();
    $variables['prefix_text'] = $state->get('giv_din_stemme.competition_header_text');
  }
}

/**
 * Implements hook_preprocess_html().
 */
function giv_din_stemme_preprocess_html(&$variables) {
  $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
}

/**
 * Implements hook_preprocess_status_messages().
 */
function giv_din_stemme_preprocess_status_messages(&$variables) {
  $currentUser = \Drupal::currentUser();

  // Do not show messages to end user in this theme.
  // @todo Design/theme messages if we want to show them some day.
  if (!in_array('editor', $currentUser->getRoles()) && $currentUser->id() !== '1') {
    unset($variables['message_list']);
  }
}
