<?php

/**
 * @file
 * Hooks for giv din stemme module.
 */

/**
 * Implements hook_theme().
 */
function giv_din_stemme_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'giv_din_stemme' => [
      'variables' => [
        'test_variable' => 'TEST VARIABLE',
//        'logout_url' => NULL,
//        'name' => NULL,
      ],
      'template' => 'giv_din_stemme',
    ],
    'landing_page' => [
      'variables' => [],
      'template' => 'landing-page',
    ],
    'consent_page' => [
      'variables' => [],
      'template' => 'consent-page',
    ],
    'oidc_login_page' => [
      'variables' => [
        'url' => NULL
      ],
      'template' => 'oidc-login-page',
    ],
    'giv_din_stemme_profile_form' => [
      'render element' => 'form',
    ],
    'permissions_page' => [
      'variables' => [],
      'template' => 'permissions-page',
    ],
    'test_page' => [
      'variables' => [],
      'template' => 'test-page',
    ],
    'donate_page' => [
      'variables' => [],
      'template' => 'donate-page',
    ],
    'read_page' => [
      'variables' => [
        'textToRead' => '',
        'textId' => '',
        'nextReading' => '',
        'totalTexts' => '',
        'nextUrl' => '',
        'hasNext' => '',
      ],
      'template' => 'read-page',
    ],
  ];
}


function giv_din_stemme_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#form_id'])) {
    $suggestions[] = 'form__' . $variables['element']['#form_id'];
  };
}
