<?php

/**
 * @file
 * Hooks for giv din stemme module.
 */

/**
 * Implements hook_theme().
 */
function giv_din_stemme_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'giv_din_stemme' => [
      'variables' => [
        'test_variable' => 'TEST VARIABLE',
//        'logout_url' => NULL,
//        'name' => NULL,
      ],
      'template' => 'giv_din_stemme',
    ],
    'landing_page' => [
      'variables' => [
        'name' => 'LANDING PAGE',
      ],
      'template' => 'landing_page',
    ],
    'consent_page' => [
      'variables' => [
        'name' => 'CONSENT PAGE',
      ],
      'template' => 'consent_page',
    ],
    'giv_din_stemme_profile_form' => [
      'render element' => 'form',
    ],
  ];
}


function giv_din_stemme_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#form_id'])) {
    $suggestions[] = 'form__' . $variables['element']['#form_id'];
  };
}