<?php

use Drupal\Core\Session\AccountInterface;
use Drupal\itk_openid_connect_interpreter\Helper\Helper;

/**
 * Implements hook_openid_connect_userinfo_alter()
 */
function itk_openid_connect_interpreter_openid_connect_userinfo_alter(array &$userinfo, array $context) {
  \Drupal::service(Helper::class)->openidConnectUserinfoAlter($userinfo, $context);
}

function itk_openid_connect_interpreter_user_format_name_alter(&$name, AccountInterface $account) {
  \Drupal::service(Helper::class)->alterUsername($name, $account);
}